version: '3.8'

services:
  mysql:
    image: mysql:lts
    container_name: forumhub-db
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
